;;; naquadah-theme.el --- A color theme

;; Copyright (C) 2011 Julien Danjou

;; Authors: Julien Danjou <julien@danjou.info>

;; This file is NOT part of GNU Emacs.

;; GNU Emacs is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; GNU Emacs is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs.  If not, see <http://www.gnu.org/licenses/>.

;;; Code:

(deftheme naquadah
  "Naquadah theme.")

(let ((light-blue "#72A0CF")
      (pale-yellow "#D4F77F")
      (violet "#C66CD0")
      (green "#89E234")
      (blue "#1144AA")
      (yellow "#FCCD3A")
      (pink "#DE336D")
      (red "#8A0B0B")
      (violet-blue "#5337AD")
      (orange "#FFA500")
      (tomato "#FC683A")
      (background "#252A2B")
      (shadow "#888a85"))
  (custom-theme-set-faces
   'naquadah
   `(default ((((min-colors 4096)) (:background ,background :foreground "#eeeeec"))))
   `(shadow ((t (:foreground ,shadow))))
   '(cursor ((t (:background "#aa0000"))))
   '(hl-line ((t (:background "#191919"))))
   `(highlight ((t (:background ,red))))
   '(fringe ((t (:background "gray10"))))
   '(mode-line ((t (:foreground "#fafafa" :background "#000000" :box (:line-width 1 :color "#444444")))))
   '(mode-line-inactive ((t (:foreground "#888888" :background "#2c2f2f" :box (:line-width 1 :color "black")))))
   `(mode-line-buffer-id ((t (:bold t :foreground ,orange))))
   '(header-line ((t (:foreground "#dddddd" :background "#1e2426" :box (:line-width 1 :color "#444444")))))
   '(region ((t (:background "grey30"))))
   `(link ((t (:underline t :foreground ,light-blue))))
   '(custom-link ((t (:inherit 'link))))
   '(match ((t (:bold t :background "#e9b96e" :foreground "#2e3436"))))
   '(tooltip ((t (:inherit 'variable-pitch :foreground "LightYellow" :background "black"))))
   '(bold ((t (:bold t :underline nil :background nil))))
   '(italic ((t (:italic t :underline nil :background nil))))
   `(font-lock-builtin-face ((t (:foreground ,light-blue))))
   '(font-lock-comment-face ((t (:inherit 'shadow :italic t))))
   '(font-lock-comment-delimiter-face ((t (:inherit 'font-lock-comment-face))))
   `(font-lock-constant-face ((t (:foreground ,green))))
   '(font-lock-doc-face ((t (:inherit 'shadow))))
   '(font-lock-keyword-face ((t (:inherit 'font-lock-builtin-face :bold t))))
   `(font-lock-string-face ((t (:foreground ,violet))))
   '(font-lock-type-face ((t (:inherit 'font-lock-constant-face :bold t))))
   `(font-lock-variable-name-face ((t (:foreground ,tomato))))
   `(font-lock-warning-face ((t (:bold t :foreground ,orange))))
   `(font-lock-function-name-face ((t (:foreground ,yellow :bold t))))
   '(comint-highlight-input ((t (:italic t :bold t))))
   `(comint-highlight-prompt ((t (:foreground ,green))))
   `(isearch ((t (:background ,orange :foreground ,background))))
   `(show-paren-match-face ((t (:background ,green))))
   `(show-paren-mismatch-face ((t (:background ,violet))))
   `(minibuffer-prompt ((t (:foreground ,light-blue :bold t))))
   `(info-xref ((t (:foreground ,light-blue))))
   `(info-xref-visited ((t (:foreground ,violet))))
   '(widget-button ((t (:bold t))))
   `(widget-mouse-face ((t (:bold t :foreground "white" :background ,red))))
   `(widget-field ((t (:foreground ,orange :background "gray30"))))
   `(widget-single-line-field ((t (:foreground ,orange :background "gray30"))))
   `(custom-group-tag ((t (:bold t :foreground ,orange :height 1.3))))
   '(custom-variable-tag ((t (:bold t :foreground "#edd400" :height 1.1))))
   '(custom-face-tag ((t (:bold t :foreground "#edd400" :height 1.1))))
   `(custom-state-face ((t (:foreground ,light-blue))))
   '(custom-button  ((t (:box (:line-width 1 :style released-button) :background "gray50" :foreground "black"))))
   '(custom-variable-button ((t (:inherit 'custom-button))))
   '(custom-button-mouse  ((t (:inherit 'custom-button :background "gray60"))))
   '(custom-button-unraised  ((t (:background "gray50" :foreground "black"))))
   '(custom-button-mouse-unraised  ((t (:inherit 'custom-button-unraised :background "gray60"))))
   '(custom-button-pressed  ((t (:inherit 'custom-button :box (:style pressed-button)))))
   '(custom-button-mouse-pressed-unraised  ((t (:inherit 'custom-button-unraised :background "gray60"))))
   '(custom-documentation ((t (:italic t))))
   '(gnus-cite-face-1 ((t (:foreground "#ad7fa3"))))
   '(gnus-cite-face-2 ((t (:foreground "sienna3"))))
   '(gnus-cite-face-3 ((t (:foreground "khaki4"))))
   '(gnus-cite-face-4 ((t (:foreground "PaleTurquoise4"))))
   '(gnus-header-name-face ((t (:bold t :foreground "#729fcf"))))
   '(gnus-header-from ((t (:bold t :foreground "#e0d400"))))
   '(gnus-header-subject ((t (:foreground "#e0d400"))))
   '(gnus-header-content ((t (:italic t :foreground "#8ae234"))))
   `(gnus-header-newsgroups-face ((t (:italic t :bold t :foreground ,light-blue))))
   '(gnus-signature-face ((t (:italic t :foreground "OliveDrab1"))))
   `(gnus-summary-cancelled-face ((t (:background "black" :foreground ,yellow))))
   '(gnus-summary-normal-ancient-face ((t (:foreground "medium sea green"))))
   '(gnus-summary-normal-read-face ((t (:foreground "lime green"))))
   `(gnus-summary-normal-ticked-face ((t (:foreground ,tomato))))
   '(gnus-summary-normal-unread-face ((t (:foreground "white"))))
   '(gnus-summary-high-ancient-face ((t (:inherit 'gnus-summary-normal-ancient-face))))
   '(gnus-summary-high-read-face ((t (:inherit 'gnus-summary-normal-read-face))))
   `(gnus-summary-high-ticked-face ((t (:inherit 'gnus-summary-normal-ticked-face))))
   '(gnus-summary-high-unread-face ((t (:inherit 'gnus-summary-normal-unread-face))))
   '(gnus-summary-low-ancient-face ((t (:inherit 'gnus-summary-normal-ancient-face) :italic t)))
   '(gnus-summary-low-read-face ((t (:inherit 'gnus-summary-normal-read-face :italic t))))
   '(gnus-summary-low-ticked-face ((t (:inherit 'gnus-summary-normal-ticked-face :italic t))))
   '(gnus-summary-low-unread-face ((t (:inherit 'gnus-summary-normal-unread-face :italic t))))
   '(spam-face ((t (:background "black" :foreground "magenta3"))))
   `(gnus-summary-selected ((t (:background ,light-blue :foreground "black"))))
   '(message-header-name-face ((t (:foreground "#729cfc"))))
   `(message-header-newsgroups-face ((t (:italic t :bold t :foreground ,light-blue))))
   '(message-header-other-face ((t (:foreground "LightSkyBlue3"))))
   '(message-header-xheader-face ((t (:foreground "DodgerBlue3"))))
   '(message-header-subject ((t (:foreground "white"))))
   '(message-header-to ((t (:foreground "white"))))
   '(message-header-cc ((t (:foreground "white"))))
   '(org-hide ((t (:foreground "#252a2b"))))
   '(org-level-1 ((t (:bold t :foreground "#4788cc" :height 1.2))))
   '(org-level-2 ((t (:bold t :foreground "#6ac214" :height 1.1))))
   '(org-level-3 ((t (:bold t :foreground "#edd400" :height 1.0))))
   '(org-level-4 ((t (:bold t :foreground "tomato" :height 1.0))))
   '(org-footnote  ((t (:underline t :foreground "magenta3"))))
   '(org-link ((t (:foreground "SkyBlue2"))))
   '(org-special-keyword ((t (:foreground "brown1"))))
   '(org-verbatim ((t (:foreground "#eeeeec" :underline t :slant italic))))
   '(org-block ((t (:foreground "#bbbbbc"))))
   '(org-quote ((t (:inherit org-block :slant italic))))
   '(org-verse ((t (:inherit org-block :slant italic))))
   '(org-todo ((t (:bold t :foreground "#ff2020"))))
   '(org-done ((t (:bold t :foreground "forest green"))))
   '(org-mode-line-clock ((t (:foreground "#cc77ff" :background nil))))
   '(org-date ((t (:underline nil :foreground "#edd466" :background nil))))
   '(org-agenda-date ((t (:underline nil :foreground "SkyBlue2" :height 1.2))))
   '(org-agenda-date-today ((t (:inherit org-agenda-date :foreground "#edd466" :weight bold))))
   '(org-agenda-date-telecommuting ((t (:inherit org-agenda-date :foreground "#ffbb22" :weight bold))))
   '(org-agenda-date-weekend ((t (:inherit org-agenda-date :foreground "brown3" :weight bold))))
   '(anything-header ((t (:bold t :background "gray15" :foreground "#edd400"))))
   '(egocentric-face ((t (:foreground "#ff4289" :weight bold))))
   '(erc-direct-msg-face ((t (:foreground "#ee5577"))))
   '(erc-header-line ((t (:background "black" :foreground "white"))))
   '(erc-input-face ((t (:foreground "gray70"))))
   '(erc-my-nick-face ((t (:inherit egocentric-face :weight thin :foreground nil))))
   '(erc-notice-face ((t (:foreground "light blue" :weight thin))))
   '(erc-prompt-face ((t (:background "black" :foreground "gray80" :weight bold))))
   '(erc-timestamp-face ((t (:foreground "gray70" :weight bold))))
   '(erc-pal-face ((t (:foreground "DarkOliveGreen3" :weight bold))))
   '(erc-fool-face ((t (:foreground "gray60" :weight thin))))
   '(erc-current-nick-face ((t (:inherit egocentric-face :weight thin :foreground nil))))
   '(ido-subdir ((t (:foreground "orange1"))))
   '(which-func ((t (:foreground "#729cfc"))))
   '(mm-uu-extract ((t (:background "#404040"))))
   `(diff-added ((t (:foreground ,green))))
   `(diff-changed ((t (:foreground ,orange))))
   `(diff-removed ((t (:foreground ,red))))
   '(diff-hunk-header ((t (:bold t))))
   `(diff-function ((t (:foreground ,orange))))
   '(diff-header ((t (:background "grey10"))))
   '(diff-file-header ((t (:background nil :foreground "white"))))
   '(git-commit-summary-face ((t (:bold t))))
   `(git-commit-branch-face ((t (:foreground ,orange :bold t))))
   '(git-commit-nonempty-second-line-face ((t (:foreground "red"))))
   '(git-commit-comment-face ((t (:inherit font-lock-comment-face))))
   '(git-commit-known-pseudo-header-face ((t (:inherit gnus-header-name-face))))
   '(git-commit-pseudo-header-face ((t (:inherit gnus-header-content))))
   '(rst-level-1-face ((t (:inherit org-level-1 :background nil))))
   '(rst-level-2-face ((t (:inherit org-level-2 :background nil))))
   '(rst-level-3-face ((t (:inherit org-level-3 :background nil))))
   '(rst-level-4-face ((t (:inherit org-level-4 :background nil))))))

(provide-theme 'naquadah)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; naquadah-theme.el ends here
